"""
Command line interface for the log agent harness.

Usage:
  python cli.py --initial-prompt "Investigate the error in the logs" [--mock] [--log-root ./logs]

The agent will run the debugging loop and output its findings.
"""

import argparse
import sys
import os
from pathlib import Path

from logagent.harness import AgentHarness
from logagent.tools import ToolRegistry
from logagent.logtools import LogTools
from logagent.llm import MockClient, ClaudeClient
from logagent.transcript import Transcript


def main():
    parser = argparse.ArgumentParser(description="Run the log agent harness")
    parser.add_argument(
        "--initial-prompt",
        type=str,
        required=True,
        help="Initial prompt for the agent",
    )
    parser.add_argument(
        "--log-root",
        type=str,
        default="./logs",
        help="Directory containing log files (default: ./logs)",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help="Use mock client (no API key needed)",
    )
    parser.add_argument(
        "--api-key",
        type=str,
        help="Anthropic API key (if not using --mock)",
    )
    parser.add_argument(
        "--model",
        type=str,
        help="Model ID for Claude (default: claude-3-5-sonnet-20241022)",
    )
    parser.add_argument(
        "--max-turns",
        type=int,
        default=10,
        help="Maximum number of agent turns (default: 10)",
    )
    parser.add_argument(
        "--max-tool-calls",
        type=int,
        default=20,
        help="Maximum number of tool calls (default: 20)",
    )
    parser.add_argument(
        "--max-output-tokens",
        type=int,
        default=5000,
        help="Maximum output tokens generated by LLM (default: 5000)",
    )
    parser.add_argument(
        "--no-transcript",
        action="store_true",
        help="Disable transcript output",
    )

    args = parser.parse_args()

    # Set up transcript
    transcript = Transcript(enabled=not args.no_transcript)

    # Set up log tools
    log_tools = LogTools(log_root=args.log_root)

    # Set up tool registry and register tools
    registry = ToolRegistry()
    # We'll register each tool from log_tools
    # list_logs
    registry.register_tool(
        name="list_logs",
        description="List log files in the log root with their sizes. Use this to discover what logs are available.",
        parameters={
            "type": "object",
            "properties": {
                "pattern": {
                    "type": "string",
                    "description": "Glob pattern to match log files (relative to log root), default '*'",
                }
            },
            "additionalProperties": False,
        },
        function=log_tools.list_logs,
        dangerous=False,
    )
    # search_logs
    registry.register_tool(
        name="search_logs",
        description="Search log files with a regex pattern. Returns matching lines with context. Use this to find specific error messages or patterns.",
        parameters={
            "type": "object",
            "properties": {
                "pattern": {
                    "type": "string",
                    "description": "Regular expression pattern to search for",
                },
                "files": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of log files to search (relative to log root). If not provided, all logs are searched.",
                },
                "context_lines": {
                    "type": "integer",
                    "description": "Number of context lines to include around each match (default: 0)",
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of matches to return (default: 100)",
                },
            },
            "required": ["pattern"],
            "additionalProperties": False,
        },
        function=log_tools.search_logs,
        dangerous=False,
    )
    # read_log
    registry.register_tool(
        name="read_log",
        description="Read a log file with pagination by line range. Use this to examine specific parts of a log file.",
        parameters={
            "type": "object",
            "properties": {
                "file": {
                    "type": "string",
                    "description": "Log file path relative to log root",
                },
                "start_line": {
                    "type": "integer",
                    "description": "1-indexed start line (default: 1)",
                },
                "end_line": {
                    "type": "integer",
                    "description": "1-indexed end line (inclusive, default: start_line + 99)",
                },
            },
            "required": ["file"],
            "additionalProperties": False,
        },
        function=log_tools.read_log,
        dangerous=False,
    )
    # log_stats
    registry.register_tool(
        name="log_stats",
        description="Compute statistics on log files: severity counts (ERROR, WARN, INFO, DEBUG) and errors-over-time histogram (hourly buckets).",
        parameters={
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of log files to analyze (relative to log root). If not provided, all logs are used.",
                },
            },
            "additionalProperties": False,
        },
        function=log_tools.log_stats,
        dangerous=False,
    )
    # timeline
    registry.register_tool(
        name="timeline",
        description="Merge several log files into one chronological view around a timestamp. Use this to correlate events across multiple logs.",
        parameters={
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of log files to merge (relative to log root)",
                },
                "around": {
                    "type": "string",
                    "description": "Center timestamp in format 'YYYY-MM-DD HH:MM:SS'",
                },
                "window": {
                    "type": "string",
                    "description": "Time window around the timestamp (format HH:MM:SS or seconds), default '00:05:00' (5 minutes)",
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of lines to return (default: 100)",
                },
            },
            "required": ["files", "around"],
            "additionalProperties": False,
        },
        function=log_tools.timeline,
        dangerous=False,
    )

    # Set up LLM client
    if args.mock:
        llm_client = MockClient(plan=[])  # We'll need to define a plan for the mock
        # For demonstration, we'll create a simple plan that uses the tools
        # But we want the mock to be generic for testing; we'll leave it empty and
        # the mock will just stop immediately. We'll improve this in the test.
        # Actually, we'll set the plan later in the test.
        pass
    else:
        if not args.api_key:
            print("Error: --api-key is required when not using --mock", file=sys.stderr)
            sys.exit(1)
        llm_client = ClaudeClient(api_key=args.api_key, model=args.model)

    # Set up agent harness
    harness = AgentHarness(
        transcript=transcript,
        tool_registry=registry,
        llm_client=llm_client,
        max_turns=args.max_turns,
        max_tool_calls=args.max_tool_calls,
        max_output_tokens=args.max_output_tokens,
    )

    # Run the agent
    print(f"Starting agent with initial prompt: {args.initial_prompt}")
    print(f"Log root: {args.log_root}")
    print(f"Using {'mock' if args.mock else 'real'} LLM client")
    result = harness.run(args.initial_prompt)

    print("\n" + "="*60)
    print("Agent finished.")
    print("="*60)
    print("Final answer:")
    print(result)


if __name__ == "__main__":
    main()