"""
Agent harness for debugging production logs.

The main loop follows the pattern:
  while stop_reason == "tool_use":
      get completion from LLM
      if stop_reason is "tool_use":
          execute tools
          collect results
          append assistant message and user message (with tool results) to history
      else:
          break

We implement brakes:
  - max_turns: limit on agent steps
  - max_tool_calls: limit on total tool calls across all turns
  - max_output_tokens: limit on cumulative tokens generated by the LLM

Tools have a 'dangerous' flag. If dangerous, we call an approve() hook (which
can be overridden) to get user permission. If refused, we return a tool result
with is_error: True and a message telling the model the user declined.

We append the assistant's content list verbatim (including thinking blocks) to
the message history so the model sees its own reasoning.

When a turn has multiple tool calls, we collect all results and put them in
a single user message with role "user" and content being a list of tool result
blocks.

We also handle pause_turn: if the LLM returns pause_turn, we break the loop
and return control to the caller.

The harness is designed to work with a ToolRegistry (from tools.py) and an
LLM client (from llm.py) that has a complete() method returning a dict with:
  - stop_reason: one of "tool_use", "pause_turn", "max_tokens", "stop"
  - content: list of content blocks (each block is a dict)
"""

import sys
from typing import List, Dict, Any, Optional

from .tools import ToolRegistry, ToolResult
from .llm import LLMClient
from .transcript import Transcript


class AgentHarness:
    def __init__(
        self,
        transcript: Transcript,
        tool_registry: ToolRegistry,
        llm_client: LLMClient,
        *,
        max_turns: int = 10,
        max_tool_calls: int = 20,
        max_output_tokens: int = 5000,
        approve_hook: Optional[callable] = None,
    ):
        self.transcript = transcript
        self.tool_registry = tool_registry
        self.llm_client = llm_client
        self.max_turns = max_turns
        self.max_tool_calls = max_tool_calls
        self.max_output_tokens = max_output_tokens
        self.approve_hook = approve_hook or self._default_approve

        # State
        self.turn_count = 0
        self.tool_call_count = 0
        self.output_token_count = 0
        self.messages: List[Dict[str, Any]] = []  # conversation history

    def _default_approve(self, tool_name: str, tool_input: Dict[str, Any]) -> bool:
        """Default approval: always allow. Override for interactivity."""
        return True

    def run(self, initial_prompt: str) -> str:
        """Run the agent loop with initial_prompt."""
        # Start conversation with user message
        self.messages = [{"role": "user", "content": initial_prompt}]
        self.transcript.start(session_id="agent-session")

        while self.turn_count < self.max_turns:
            self.turn_count += 1
            self.transcript.log_turn_start(self.turn_count)

            # Get completion from LLM
            completion = self.llm_client.complete(
                messages=self.messages,
                max_tokens=self.max_output_tokens - self.output_token_count,
                stop_sequences=["\n\nHuman:", "\n\nAssistant:"],
            )

            # Update token count (approximate)
            # In a real implementation, we'd get token usage from the response
            # For now, we'll estimate by counting words (very rough)
            # But we have a mock that returns token usage, so we'll use that if available
            if "usage" in completion and "output_tokens" in completion["usage"]:
                self.output_token_count += completion["usage"]["output_tokens"]
            else:
                # Fallback: estimate 4 chars per token
                content_str = str(completion.get("content", ""))
                self.output_token_count += len(content_str) // 4

            stop_reason = completion.get("stop_reason")
            content_blocks = completion.get("content", [])

            # Log the assistant's turn
            self.transcript.log_assistant_turn(content_blocks, stop_reason)

            # Append assistant's content verbatim to messages
            self.messages.append(
                {"role": "assistant", "content": content_blocks}
            )

            # Handle stop reasons
            if stop_reason == "tool_use":
                # Execute tools
                tool_results = self._execute_tool_calls(content_blocks)
                # Append tool results as a single user message
                if tool_results:
                    self.messages.append(
                        {
                            "role": "user",
                            "content": tool_results,
                        }
                    )
                    self.transcript.log_tool_results(tool_results)
                # Continue loop
            elif stop_reason == "pause_turn":
                self.transcript.log_pause_turn()
                break
            else:
                # max_tokens, stop, etc.
                self.transcript.log_final_stop(stop_reason)
                break

        # Return the last assistant message content as string
        if self.messages and self.messages[-1]["role"] == "assistant":
            # Concatenate text blocks for simplicity
            text_blocks = [
                block.get("text", "")
                for block in self.messages[-1]["content"]
                if block.get("type") == "text"
            ]
            return "\n".join(text_blocks)
        return ""

    def _execute_tool_calls(
        self, content_blocks: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Execute tool calls from content blocks and return tool result blocks."""
        tool_calls = []
        for block in content_blocks:
            if block.get("type") == "tool_use":
                tool_calls.append(
                    {
                        "id": block.get("id"),
                        "name": block.get("name"),
                        "input": block.get("input", {}),
                    }
                )

        if not tool_calls:
            return []

        # Check tool call limit
        if self.tool_call_count + len(tool_calls) > self.max_tool_calls:
            # Too many tool calls, return error for each
            return [
                {
                    "type": "tool_result",
                    "tool_use_id": call["id"],
                    "content": [
                        {
                            "type": "text",
                            "text": f"Error: Exceeded max tool calls ({self.max_tool_calls}).",
                        }
                    ],
                    "is_error": True,
                }
                for call in tool_calls
            ]

        self.tool_call_count += len(tool_calls)

        results = []
        for call in tool_calls:
            tool_name = call["name"]
            tool_input = call["input"]
            tool_use_id = call["id"]

            # Check if tool is dangerous and needs approval
            tool = self.tool_registry.get_tool(tool_name)
            if tool and tool.get("dangerous", False):
                if not self.approve_hook(tool_name, tool_input):
                    results.append(
                        {
                            "type": "tool_result",
                            "tool_use_id": tool_use_id,
                            "content": [
                                {
                                    "type": "text",
                                    "text": f"User declined execution of dangerous tool '{tool_name}'.",
                                }
                            ],
                            "is_error": True,
                        }
                    )
                    continue

            # Execute tool
            try:
                tool_result = self.tool_registry.execute_tool(
                    tool_name, tool_input
                )
                # ToolResult is a dict with keys: content, is_error, etc.
                # We expect the tool to return a list of content blocks
                # and optionally is_error flag
                if isinstance(tool_result, dict) and "content" in tool_result:
                    content = tool_result["content"]
                    is_error = tool_result.get("is_error", False)
                else:
                    # Assume it's a list of content blocks
                    content = tool_result if isinstance(tool_result, list) else []
                    is_error = False

                results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": tool_use_id,
                        "content": content,
                        "is_error": is_error,
                    }
                )
                self.transcript.log_tool_call(
                    tool_name, tool_input, content, is_error
                )
            except Exception as e:
                # Tool execution failed
                error_msg = f"Tool '{tool_name}' failed: {str(e)}"
                results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": tool_use_id,
                        "content": [{"type": "text", "text": error_msg}],
                        "is_error": True,
                    }
                )
                self.transcript.log_tool_error(tool_name, tool_input, str(e))

        return results